app = "by-money-backend"
primary_region = "gig"


[build]
builder = "paketobuildpacks/builder:base"


[env]
PORT = "8080"


[http_service]
internal_port = 8_080
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 1
processes = [ "app" ]


[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
